# trigger:
#   branches:
#     include:
#       - main

# pool:
#   vmImage: 'ubuntu-latest'


# stages:
#   - stage: Deploy
#     jobs:
#       - job: Asdatest
#         steps:
#           - checkout: self
#             clean: true

#           - task: InstallSSHKey@0
#             displayName: 'Add SSH key for AsdaCloudProductLibrary'
#             inputs:
#               knownHostsEntry: "github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk="
#               sshKeySecureFile: 'id_rsa'

#           - task: TerraformTaskV4@4
#             displayName: 'Terraform Init'
#             inputs:
#               provider: 'azurerm'
#               command: 'init'
#               backendServiceArm: "Asda-serconn"
#               backendConfig: |
#                 subscription_id: "09b27316-79bc-4c82-8c9f-7d36527f6142" #{{ parameters.tf_subscription_id }}
#                 tenant_id: "fbbc769d-4de6-40e9-af32-78116ef7033d" #$(tenantId)
#                 client_id: "9af1ae6b-19c1-4412-97a0-3ee366d2944f"
#                 client_secret: "1vM8Q~SMTNvPlr4r35jtbpiou2XyLtOb0cC5mbKK"
#               backendAzureRmResourceGroupName: '$(resource_group_name)' #$'Asda' 
#               backendAzureRmStorageAccountName: '$(storage_account_name)' #'asda123'
#               backendAzureRmContainerName: '$(container_name )' #'tfuser123'
#               backendAzureRmKey: '$(key)' #'asda.terraform.tfstate'
#               backendAzureRMAccessKey: '$(access_key)'

#           - task: TerraformTaskV4@4
#             displayName: 'Terraform Validate'
#             inputs:
#               provider: 'azurerm'
#               command: 'validate'

#           - task: TerraformTaskV4@4
#             displayName: 'Terraform Format'
#             inputs:
#               provider: 'azurerm'
#               command: 'custom'
#               customCommand: 'fmt'
#               outputTo: 'console'
#               environmentServiceNameAzureRM: "Asda-serconn" 

#           - task: TerraformTaskV4@4
#             displayName: 'Terraform Plan'
#             inputs:
#               provider: 'azurerm'
#               command: 'plan'
#               commandOptions: '-out $(Build.SourcesDirectory)/tfplanfile'
#               environmentServiceNameAzureRM: "Asda-serconn"

#           - task: TerraformTaskV4@4
#             displayName: 'Terraform Apply'
#             inputs:
#               provider: 'azurerm'
#               command: 'apply'
#               commandOptions: '-auto-approve $(Build.SourcesDirectory)/tfplanfile'
#               environmentServiceNameAzureRM: "Asda-serconn"

          # - task: TerraformTaskV4@4
          #   displayName: 'Terraform Destroy'
          #   inputs:
          #     provider: 'azurerm'
          #     command: 'destroy'
          #     commandOptions: '-auto-approve $(Build.SourcesDirectory)/tfplanfile'
          #     environmentServiceNameAzureRM: "Asda-serconn"





trigger: none
 #- feature/*

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
      clean: true

    - task: InstallSSHKey@0
      displayName: Add SSH key for AsdaCloudProductLibrary
      inputs:
        knownHostsEntry: "github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk="
        sshKeySecureFile: 'id_rsa'
        
    - task: TerraformTaskV4@4
      displayName: Tf init
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'Asda-serconn' #"9af1ae6b-19c1-4412-97a0-3ee366d2944f" #'${SERVICECONNECTION}'
        backendAzureRmResourceGroupName: 'Asda'
        backendAzureRmStorageAccountName: 'asdabackend'
        backendAzureRmContainerName: 'asda-container'
        backendAzureRmKey: 'asda.terraform.tfstate'

    - task: TerraformTaskV4@4
      displayName: Tf validate
      inputs:
        provider: 'azurerm'
        command: 'validate'

    - task: TerraformTaskV4@4
      displayName: Tf fmt
      inputs:
        provider: 'azurerm'
        command: 'custom'
        customCommand: 'fmt'
        outputTo: 'console'
        environmentServiceNameAzureRM: "Asda-serconn" #'${SERVICECONNECTION}'

    - script: |
        echo "Checking for existing Terraform lock..."
        LOCK_INFO=$(terraform force-unlock -force $(terraform force-unlock -list | grep -oP '(?<=ID: )[^\s]+') || true)
        if [ -n "$LOCK_INFO" ]; then
          echo "Unlocking Terraform state with lock ID: $LOCK_INFO"
        else
          echo "No existing lock found, proceeding..."
        fi
      displayName: 'Force Unlock State if Locked'
      
    - task: TerraformTaskV4@4
      displayName: Tf plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        commandOptions: '-lock=false -out $(Build.SourcesDirectory)/tfplanfile'
        environmentServiceNameAzureRM: "Asda-serconn" #'${SERVICECONNECTION}'
    

    - task: TerraformTaskV4@4
      displayName: Tf Apply
      inputs:
        provider: 'azurerm'
        command: 'apply'
        commandOptions: '-lock=false -input=false -auto-approve $(Build.SourcesDirectory)/tfplanfile'
        environmentServiceNameAzureRM: "Asda-serconn" #'${SERVICECONNECTION}'

    
